export const theme = {
  colors: {
    primary: '#4CAF50',
    primaryContainer: '#C8E6C9',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#1B5E20',
    secondary: '#26C6DA',
    secondaryContainer: '#5CE9FE',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#006773',
    tertiary: '#AB47BC',
    tertiaryContainer: '#F189FF',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#750689',
    background: '#FCF9F8',
    surface: '#FCF9F8',
    surfaceVariant: '#E5E2E1',
    onSurface: '#1C1B1B',
    onSurfaceVariant: '#554434',
    outline: '#887361',
    outlineVariant: '#DBC2AD',
    inverseSurface: '#313030',
    inverseOnSurface: '#F3F0EF',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    // Missing surface containers
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F7F2F1',
    surfaceContainer: '#F3EDEC',
    surfaceContainerHigh: '#EEE8E6',
    surfaceContainerHighest: '#E8E2E1',
    // Custom Gradients
    primaryGradient: ['#2E7D32', '#4CAF50'] as [string, string],
  },
  typography: {
    displayLarge: {
      fontFamily: 'PlusJakartaSans-Bold',
      fontSize: 57,
      letterSpacing: -1.14,
    },
    displayMedium: {
      fontFamily: 'PlusJakartaSans-Bold',
      fontSize: 45,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: 'PlusJakartaSans-Bold',
      fontSize: 36,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: 'PlusJakartaSans-SemiBold',
      fontSize: 32,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: 'PlusJakartaSans-SemiBold',
      fontSize: 28,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: 'PlusJakartaSans-SemiBold',
      fontSize: 24,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: 'PlusJakartaSans-Medium',
      fontSize: 22,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: 'PlusJakartaSans-Medium',
      fontSize: 16,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: 'PlusJakartaSans-Medium',
      fontSize: 14,
      letterSpacing: 0.1,
    },
    bodyLarge: {
      fontFamily: 'Inter-Regular',
      fontSize: 16,
      letterSpacing: 0.15,
    },
    bodyMedium: {
      fontFamily: 'Inter-Regular',
      fontSize: 14,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: 'Inter-Regular',
      fontSize: 12,
      letterSpacing: 0.4,
    },
    labelLarge: {
      fontFamily: 'Inter-Medium',
      fontSize: 14,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: 'Inter-Medium',
      fontSize: 12,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: 'Inter-Medium',
      fontSize: 11,
      letterSpacing: 0.55,
      textTransform: 'uppercase' as const,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  roundness: 8,
  elevation: {
    low: {
      shadowColor: '#1C1B1B',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#1C1B1B',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    high: {
      shadowColor: '#1C1B1B',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 24,
      elevation: 6,
    },
    highest: {
      shadowColor: '#1C1B1B',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.15,
      shadowRadius: 32,
      elevation: 8,
    },
    ambient: {
      shadowColor: '#1C1B1B',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 4,
    },
  },
  glass: {
    backgroundColor: 'rgba(229, 226, 225, 0.7)',
    backdropFilter: 'blur(20px)',
  }
};
